# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=30)),
                ('profile_picture', models.URLField(blank=True)),
                ('profile_picture_url', models.ImageField(blank=True, upload_to='profile_pics')),
                ('full_name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=150)),
                ('website', models.URLField(blank=True)),
                ('is_business', models.BooleanField(default=False)),
                ('media_count', models.IntegerField(default=0)),
                ('follows_count', models.IntegerField(default=0)),
                ('folowed_by_count', models.IntegerField(default=0)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('follows_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
