# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True),
        ),
    ]
