# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170917_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows_list',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
