# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_follows_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
