# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_follows_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='follows_list',
            field=models.ManyToManyField(null=True, related_name='follows', to='user.Profile'),
        ),
    ]
