# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170918_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows_list',
        ),
    ]
