# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.FloatField(unique=True),
        ),
    ]
