# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 23:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poll.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(default='image', max_length=10)),
                ('poll_media_count', models.IntegerField(default=2)),
                ('link', models.URLField(blank=True)),
                ('media_a', models.ImageField(upload_to=poll.models.path_and_rename_a)),
                ('media_b', models.ImageField(upload_to=poll.models.path_and_rename_b)),
                ('vote_a_count', models.IntegerField(default=0)),
                ('vote_b_count', models.IntegerField(default=0)),
                ('caption', models.CharField(max_length=2200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('a', 'mediaA'), ('b', 'mediaB')], max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_for', to='poll.Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_on', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
