# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 03:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20170917_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='caption',
            field=models.CharField(blank=True, max_length=2200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='media_type',
            field=models.CharField(blank=True, default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_media_count',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='poll',
            name='user_vote',
            field=models.ManyToManyField(blank=True, through='poll.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='vote_a_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='vote_b_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
