# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_remove_poll_user_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_for', to='poll.Poll'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_on', to=settings.AUTH_USER_MODEL),
        ),
    ]
