# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20170917_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='media_a',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='poll',
            name='media_b',
            field=models.FileField(upload_to=''),
        ),
    ]
